CREATE TABLE "BSX"."ITEM" (
	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"Code" NVARCHAR2(2000) NOT NULL ENABLE, 
	"Name" NVARCHAR2(2000) NOT NULL ENABLE, 
	"Type" NVARCHAR2(2000) NOT NULL ENABLE, 
	"Price" FLOAT(38) NOT NULL ENABLE, 
	"Quantity" NUMBER(38,0) NOT NULL ENABLE, 
	"Date" DATE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_ITEM_TYPE" FOREIGN KEY ("Type")
	  REFERENCES "BSX"."TYPE" ("Name") ON DELETE CASCADE ENABLE
   )

CREATE TABLE "BSX"."TYPE" (
	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"Name" NVARCHAR2(2000) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TYPE" PRIMARY KEY ("Name")
  USING INDEX  ENABLE
   )
